#ifndef JOURNALD_H
#define JOURNALD_H

typedef enum JournalField
{
    JOURNAL_FIELD_PRIORITY,
    JOURNAL_FIELD_MESSAGE,
    JOURNAL_FIELD_TIMESTAMP,
    JOURNAL_FIELD_PID,
    JOURNAL_FIELD_UID,
    JOURNAL_FIELD_GID,
    JOURNAL_FIELD_COMM,
    JOURNAL_FIELD_EXE,
    JOURNAL_FIELD_SYSTEMD_UNIT,
    JOURNAL_FIELD_SYSTEMD_USER_UNIT,
    JOURNAL_FIELD_BOOT_ID,
    JOURNAL_FIELD_MACHINE_ID,
    JOURNAL_FIELD_HOSTNAME,
    JOURNAL_FIELD_TRANSPORT,

    JOURNAL_FIELD_COUNT
} JournalField;

#endif
